export const VIEWER_LIST_REQUEST = "VIEWER_LIST_REQUEST";
export const VIEWER_LIST_SUCCESS = "VIEWER_LIST_SUCCESS";
export const VIEWER_LIST_FAIL = "VIEWER_LIST_FAIL";

export const VIEWER_DETAILS_REQUEST = "VIEWER_DETAILS_REQUEST";
export const VIEWER_DETAILS_SUCCESS = "VIEWER_DETAILS_SUCCESS";
export const VIEWER_DETAILS_FAIL = "VIEWER_DETAILS_FAIL";

export const VIEWER_DELETE_REQUEST = "VIEWER_DELETE_REQUEST";
export const VIEWER_DELETE_SUCCESS = "VIEWER_DELETE_SUCCESS";
export const VIEWER_DELETE_FAIL = "VIEWER_DELETE_FAIL";

export const VIEWER_STATUS_REQUEST = "VIEWER_STATUS_REQUEST";
export const VIEWER_STATUS_SUCCESS = "VIEWER_STATUS_SUCCESS";
export const VIEWER_STATUS_FAIL = "VIEWER_STATUS_FAIL";

export const VIEWER_ADD_REQUEST = "VIEWER_ADD_REQUEST";
export const VIEWER_ADD_SUCCESS = "VIEWER_ADD_SUCCESS";
export const VIEWER_ADD_FAIL = "VIEWER_ADD_FAIL";
